services:
  postgres:
    image: postgres:latest
    container_name: analytic-postgres
    environment:
      POSTGRES_USER: analytic
      POSTGRES_PASSWORD: analytic
      POSTGRES_DB: analytic_db
    ports:
      - "5434:5432"
    volumes:
      - payment_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U payment -d payment_db" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - csms-ticket-service-network
        
        
networks:
  csms-ticket-service-network:
    driver: bridge

volumes:
  payment_pg_data:
  csms-kafka-data: