services:
  postgres:
    image: postgres:latest
    container_name: analytic-postgres
    environment:
      POSTGRES_USER: analytic
      POSTGRES_PASSWORD: analytic
      POSTGRES_DB: analytic_db
    ports:
      - "5434:5432"
    volumes:
      - payment_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U analytic -d analytic_db" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - csms-ticket-service-network
  
  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: unless-stopped
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - csms-ticket-service-network

  kafka:
    image: wurstmeister/kafka:latest
    restart: unless-stopped
    environment:
      KAFKA_LOG_DIRS: /kafka-data
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://127.0.0.1:9092,INTERNAL://kafka:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CREATE_TOPICS: 
        payment_status:1:1,
        event_created:1:1,
        seat_booked:1:1,
        venue_created:1:1,
        loyalty_sum:1:1,
        user_events:1:1,
        seat_returned:1:1
    depends_on:
      - zookeeper
    networks:
      - csms-ticket-service-network
    volumes:
      - csms-kafka-data:/kafka-data
    ports:
      - '9092:9092'

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: unless-stopped
    depends_on:
      - kafka
    networks:
      - csms-ticket-service-network
    ports:
      - "8003:8080"
    volumes:
      - ../Presentation/AnalyticService.Presentation.Kafka/Protos:/schemas
    environment:
      kafka.clusters.0.name: kafka
      kafka.clusters.0.bootstrapServers: kafka:9094
      kafka.clusters.0.defaultKeySerde: ProtobufFile
      kafka.clusters.0.defaultValueSerde: ProtobufFile

      kafka.clusters.0.serde.0.name: ProtobufFile
      kafka.clusters.0.serde.0.properties.protobufFilesDir: /schemas/

      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.payment_status: payments.PaymentStatusKey
      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.payment_status: payments.PaymentStatusValue
      
      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.loyalty_sum: loyalty.PaymentsSumKey
      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.loyalty_sum: loyalty.PaymentsSumValue
      
      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.event_created: analytics.EventCreatedKey
      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.event_created: analytics.EventCreatedValue
      
      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.seat_booked: analytics.SeatsBookedKey
      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.seat_booked: analytics.SeatsBookedValue
      
      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.venue_created: analytics.VenueCreatedKey
      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.venue_created: analytics.VenueCreatedValue
      
      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.seat_returned: analytics.SeatsReturnedKey
      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.seat_returned: analytics.SeatsReturnedValue
      
      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.user_creation: users.UserEventKey
      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.user_creation: users.UserEventValue

networks:
  csms-ticket-service-network:
    driver: bridge

volumes:
  payment_pg_data:
  csms-kafka-data: